from __future__ import annotations

import numpy as np
from numpy.typing import NDArray

class _FaceImpl: ...

class Face:
    def __init__(self, face_impl: _FaceImpl) -> None: ...
    @property
    def id(self) -> int: ...
    @property
    def normal(self) -> NDArray[np.float64]: ...
    def describe(self) -> str: ...
