from __future__ import annotations

import numpy as np
from numpy.typing import ArrayLike, NDArray

class _FlatParameterisationImpl: ...

from .mesh import Mesh
from .point import Point

class FlatParameterisation:
    def __init__(self, mesh: Mesh) -> None: ...
    def is_one_to_one_mapping(self) -> bool: ...
    def project(self, point: Point) -> NDArray[np.float64]: ...
    def retrieve(self, uv: ArrayLike) -> Point: ...
    def is_inside_mesh(self, uv: ArrayLike) -> bool: ...
    def min_uv(self) -> NDArray[np.float64]: ...
    def max_uv(self) -> NDArray[np.float64]: ...
