from __future__ import annotations

from typing import Optional

import numpy as np
from numpy.typing import ArrayLike, NDArray

class _MeshImpl: ...

from .face import Face
from .geodesic import Geodesic
from .point import Point
from .vertex import Vertex

class Mesh:
    def __init__(
        self,
        vertices: Optional[ArrayLike] = ...,
        faces: Optional[ArrayLike] = ...,
        mesh_impl: Optional[_MeshImpl] = ...,
    ) -> None: ...
    @staticmethod
    def load_from_file(file_path: str) -> Mesh: ...
    @staticmethod
    def mesh_directory() -> str: ...
    @staticmethod
    def cube_angle() -> Mesh: ...
    def transform(self, matrix: ArrayLike) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def num_vertices(self) -> int: ...
    @property
    def num_faces(self) -> int: ...
    def get_vertex_matrix(self) -> NDArray[np.float64]: ...
    def get_face_matrix(self) -> NDArray[np.int32]: ...
    def vertex(self, id: int) -> Vertex: ...
    def face(self, id: int) -> Face: ...
    def random_face(self) -> Face: ...
    @property
    def faces(self) -> list[Face]: ...
    @property
    def vertices(self) -> list[Vertex]: ...
    def build_geodesic(self, from_point: Point, to_point: Point) -> Geodesic: ...
    def midpoint_subdivide(self, iterations: int = 1) -> Mesh: ...
    def to_pyvista(self): ...
    def closest_vertex(self, point: ArrayLike) -> Vertex: ...
    @staticmethod
    def extract_normal_bounded_surface(
        mesh: Mesh,
        point: Point,
        max_normal_angle: float = 90.0,
    ) -> Mesh: ...
