from __future__ import annotations

import numpy as np
from numpy.typing import ArrayLike, NDArray

class _PointImpl: ...

from .vertex import Vertex

class Point:
    def __init__(self, point_impl: _PointImpl | Vertex) -> None: ...
    @classmethod
    def from_vertex(cls, vertex: Vertex) -> Point: ...
    @staticmethod
    def from_cartesian(mesh: "Mesh", position: ArrayLike) -> Point: ...
    @staticmethod
    def random(mesh: "Mesh") -> Point: ...
    @property
    def position(self) -> NDArray[np.float64]: ...
    @property
    def face(self) -> "Face": ...
    def describe(self) -> str: ...

from .face import Face
from .mesh import Mesh
