from __future__ import annotations

import numpy as np
from numpy.typing import ArrayLike, NDArray

from .point import Point

class TangentVector:
    def __init__(self, application_point: Point, vector: ArrayLike) -> None: ...
    @staticmethod
    def from_ambient_vector(
        application_point: Point, vector: ArrayLike
    ) -> TangentVector: ...
    @staticmethod
    def from_tip_position(
        application_point: Point, tip: ArrayLike
    ) -> TangentVector: ...
    @staticmethod
    def unit_random(application_point: Point) -> TangentVector: ...
    def tip(self) -> NDArray[np.float64]: ...
    def cartesian_vector(self) -> NDArray[np.float64]: ...
    def scale(self, factor: float) -> None: ...
    def normalise(self) -> None: ...
    def normalised(self) -> TangentVector: ...
    def application_point(self) -> Point: ...
    def type(self) -> int: ...
