from __future__ import annotations

import numpy as np
from numpy.typing import NDArray

class _VertexImpl: ...

class Vertex:
    def __init__(self, vertex_impl: _VertexImpl) -> None: ...
    @property
    def position(self) -> NDArray[np.float64]: ...
    @property
    def normal(self) -> NDArray[np.float64]: ...
    @property
    def id(self) -> int: ...
    def describe(self) -> str: ...
    def total_curvature(self) -> float: ...
    def gauss_curvature(self) -> float: ...
